src/Code/GenDB/Controllers/CensusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GenDB.Business.Repository;
using GenDB.Business.Repository.EntityFramework;
using GenDB.Models;

namespace GenDB.Controllers
{
  public class CensusController : Controller
  {
    private ICensusRepository _repository;

    public CensusController() : this(RepositoryFactory.CreateCensusRepository())
    {
    }

    public CensusController(ICensusRepository repository)
    {
      _repository = repository;
    }

    public ActionResult All()
    {
      return View("Search", _repository.All());
    }

    // GET: Censuses
    public ActionResult Search(SearchParameters parameters)
    {
      return (View(_repository.Search(parameters)));
    }

    // GET: Censuses/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Census census = _repository.Get(id.Value);
      if (census == null) {
        return HttpNotFound();
      }
      return View(census);
    }

#if EDITABLE
    // GET: Censuses/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Censuses/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "ID,FirstName,MiddleName,LastName,Age,DateOfRecord,Page,Town")] Census census)
    {
      if (ModelState.IsValid) {
        db.Census.Add(census);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(census);
    }

    // GET: Censuses/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Census census = db.Census.Find(id);
      if (census == null) {
        return HttpNotFound();
      }
      return View(census);
    }

    // POST: Censuses/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ID,FirstName,MiddleName,LastName,Age,DateOfRecord,Page,Town")] Census census)
    {
      if (ModelState.IsValid) {
        db.Entry(census).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(census);
    }

    // GET: Censuses/Delete/5
    public ActionResult Delete(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Census census = db.Census.Find(id);
      if (census == null) {
        return HttpNotFound();
      }
      return View(census);
    }

    // POST: Censuses/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
      Census census = db.Census.Find(id);
      db.Census.Remove(census);
      db.SaveChanges();
      return RedirectToAction("Index");
    }
#endif

    protected override void Dispose(bool disposing)
    {
      if (disposing) {
        _repository.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

src/Code/GenDB/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GenDB.Business.Repository.EntityFramework;
using GenDB.Models;
using GenDB.Business.Repository;

namespace GenDB.Controllers
{
    public class HomeController : Controller
    {
        private GenContext db = new GenContext();

        public ActionResult Index()
        {
            ViewBag.Counties = new SelectList(db.County, "ID", "Name");

            return View();
        }

        public ActionResult Search(SearchParameters searchParam)
        {
          return(View(searchParam));

        }

        [HttpGet]
        public PartialViewResult _TOSPopUp()
        {
            return PartialView();
        }
    }
}

src/Code/GenDB/Controllers/NaturalizationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GenDB.Business.Repository;
using GenDB.Business.Repository.EntityFramework;
using GenDB.Models;

namespace GenDB.Controllers
{
  public class NaturalizationController : Controller
  {
    private INaturalizationRepository _repository;

    public NaturalizationController() : this(RepositoryFactory.CreateNaturalizationRepository())
    {
    }

    public NaturalizationController(INaturalizationRepository repository)
    {
      _repository = repository;
    }

    public ActionResult All()
    {
      return View("Search", _repository.All());
    }

    // GET: Naturalizations
    public ActionResult Search(SearchParameters parameters)
    {
      return View(_repository.Search(parameters));
    }

    // GET: Naturalizations/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Naturalization naturalization = _repository.Get(id.GetValueOrDefault());
      if (naturalization == null) {
        return HttpNotFound();
      }
      return View(naturalization);
    }

#if EDITABLE
    // GET: Naturalizations/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Naturalizations/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "ID,FirstName,MiddleName,LastName,DOB,Age,DateOfRecord,Location,CountryOfOrigin,Series,Box,Folder,VolNumber,PageCertNumber,DateOfEntry,PortOfEntry")] Naturalization naturalization)
    {
      if (ModelState.IsValid) {
        db.Naturalization.Add(naturalization);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(naturalization);
    }

    // GET: Naturalizations/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Naturalization naturalization = db.Naturalization.Find(id);
      if (naturalization == null) {
        return HttpNotFound();
      }
      return View(naturalization);
    }

    // POST: Naturalizations/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ID,FirstName,MiddleName,LastName,DOB,Age,DateOfRecord,Location,CountryOfOrigin,Series,Box,Folder,VolNumber,PageCertNumber,DateOfEntry,PortOfEntry")] Naturalization naturalization)
    {
      if (ModelState.IsValid) {
        db.Entry(naturalization).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(naturalization);
    }

    // GET: Naturalizations/Delete/5
    public ActionResult Delete(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Naturalization naturalization = db.Naturalization.Find(id);
      if (naturalization == null) {
        return HttpNotFound();
      }
      return View(naturalization);
    }

    // POST: Naturalizations/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
      Naturalization naturalization = db.Naturalization.Find(id);
      db.Naturalization.Remove(naturalization);
      db.SaveChanges();
      return RedirectToAction("Index");
    }
#endif
    protected override void Dispose(bool disposing)
    {
      if (disposing) {
        _repository.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

src/Code/GenDB/Controllers/ObituaryController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GenDB.Business;
using GenDB.Models;
using PagedList;

namespace GenDB.Controllers
{
  public class ObituaryController : Controller
  {
    private ObituaryBusinessLogic _service;

    public ObituaryController()
    {
      _service = new ObituaryBusinessLogic();
    }

    /// <summary>
    /// Returns / displays all obituaries in the systme.
    /// </summary>
    /// <returns></returns>
    public ActionResult All()
    {
      return View("Search", _service.All().ToList());
    }

    // GET: Obits
    public ActionResult Search(SearchParameters parameters)
    {
      var results = _service.Search(parameters);
      // Do some additional conversion / of the data to a local UI model, etc.
      return View(results);
    }

    public ActionResult Webtext(int id)
    {
      var wt = _service.Get(id);
      return PartialView("_WTPopup", wt);
    }

    // GET: Obits/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Obit obit = _service.Get(id.GetValueOrDefault());
      if (obit == null) {
        return HttpNotFound();
      }
      return View(obit);
    }

#if EDITABLE
    // GET: Obits/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Obits/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "ID,FirstName,MiddleName,LastName,AltName,DateOfRecord,BirthDate,Age,WebText")] Obit obit)
    {
      if (ModelState.IsValid) {
        db.Obit.Add(obit);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(obit);
    }

    // GET: Obits/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Obit obit = db.Obit.Find(id);
      if (obit == null) {
        return HttpNotFound();
      }
      return View(obit);
    }

    // POST: Obits/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ID,FirstName,MiddleName,LastName,AltName,DateOfRecord,BirthDate,Age,WebText")] Obit obit)
    {
      if (ModelState.IsValid) {
        db.Entry(obit).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }
      return View(obit);
    }

    // GET: Obits/Delete/5
    public ActionResult Delete(int? id)
    {
      if (id == null) {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Obit obit = db.Obit.Find(id);
      if (obit == null) {
        return HttpNotFound();
      }
      return View(obit);
    }

    // POST: Obits/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
      Obit obit = db.Obit.Find(id);
      db.Obit.Remove(obit);
      db.SaveChanges();
      return RedirectToAction("Index");
    }
#endif

    protected override void Dispose(bool disposing)
    {
      if (disposing) {
        _service.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

src/Code/GenDB/Views/Home/Index.cshtml
@using GenDB.Models

@model SearchParameters


<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>

<br />
<div>
    <img src="~/Content/themes/base/images/libraryheader.jpg" width="1200" height="200" />
</div>

<h2>Central Wisconsin Genealogy Search</h2>
<br />
<br />


<script type="text/javascript">
    $(function () {
        $('#dialog').dialog({
            autoOpen: false,
            width: 600,
            height: 800,
            resizable: false,
            title: 'Terms of Service Agreement',
            modal: true,
            open: function(event, ui) {
                //Load the TOSPopUP action which will return
                // the partial view _TOSPopUp
                $(this).load("@Url.Action("_TOSPopUp")");
            },
            buttons: {
                "Close": function () {
                    $(this).dialog("close");
                }
            }
        });
        $('#TOS-link').click(function () {
            $('#dialog').dialog('open');
        });
    });
</script>

@* Popup for the TOS Dialog *@
<div id="dialog" title="Terms of Service Agreement" style="overflow: scroll;"></div>



<div>
    <p>Please review our <a href="#" id="TOS-link">Terms of Service Agreement</a> prior to use.</p>
</div>
<br />

@*Need to move this when we get a chance into CSS file
    5/10/18 -- Tried moving to CSS file, unable to get bundled with other CSS
    Keeping here for now to preserve functionality*@
<style type="text/css">
    .editor-label, .display-label {
        clear: both;
        float: left;
        width: 150px;
        margin: 1em 0 0 0;
        font-weight: bold;
    }

    .editor-field, .display-field {
        margin: 1em 0 0 0;
        min-height: 1.5em;
    }
</style>


<div>
    @using (Html.BeginForm("Search", "Home"))
    {
        <div>
            @Html.LabelFor(m => m.LastName, htmlAttributes: new { @class = "editor-label" })
            @Html.TextBoxFor(m => m.LastName, htmlAttributes: new { @class = "editor-field" })
        </div>
        <br />
        <div>
            @Html.LabelFor(m => m.FirstName, htmlAttributes: new { @class = "editor-label" })
            @Html.TextBoxFor(m => m.FirstName, htmlAttributes: new { @class = "editor-field" })
        </div>
        <br />
        <div width>
            @Html.LabelFor(m => m.AltName, htmlAttributes: new { @class = "editor-label" })
            @Html.TextBoxFor(m => m.AltName, htmlAttributes: new { @class = "editor-field" })
        </div>
        <br />
        <div>
            @Html.LabelFor(m => m.EventYear, htmlAttributes: new { @class = "editor-label" })
            @Html.TextBoxFor(m => m.EventYear, htmlAttributes: new { @class = "editor-field", @type = "number" })
        </div>
        <br />
        <div>
            @Html.LabelFor(m => m.County, htmlAttributes: new { @class = "editor-label" })
            @Html.DropDownListFor(m => m.County, ViewBag.Counties as IEnumerable<SelectListItem>, "- Select County -", htmlAttributes: new { @class = "editor-field" })
        </div>
        <br />
        <div>
            <button type="reset">Clear All Fields</button>
            <button type="submit">Search</button>
        </div>
    }

</div>







src/Code/GenDB/Views/Home/Search.cshtml
@model GenDB.Models.SearchParameters

<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>



<br />
<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Obituaries</a></li>
    <li><a href="#tabs-2">Naturalizations</a></li>
    <li><a href="#tabs-3">Censuses</a></li>
  </ul>

  <div id="tabs-1">
    @Html.Action("Search", "Obituary", new RouteValueDictionary() { { "parameters", Model } })
  </div>

  <div id="tabs-2">      
    @Html.Action("Search", "Naturalization", new RouteValueDictionary() { { "parameters", Model } })
  </div>

  <div id="tabs-3">
      @Html.Action("Search", "Census", new RouteValueDictionary() { { "parameters", Model } })
  </div>
</div>


@section scripts {
    <script type="text/javascript">
  $(document).ready(function() {
    //var search = @Html.Raw(Model.ToJson());
    $("#tabs").tabs({
      load: function (event, ui) {
        console.log('load the crap...');
      }
      });
        $('#tabs').css('width', '1300px');
    $('#tabs .ui-tab').bind('click', function(event) {
      console.log('tab click'+JSON.stringify(event.currentTarget));
      console.log(search);
      console.log(event);


      /*
      $.ajax({
      url: '',
      sucess: function() {

      },
      error: function() {

      }
      */
    });
  });
    </script>
}

src/Code/GenDB/Views/Home/TOSPopUp.cshtml
<h2>TOS will appear here</h2>